server:
  port: 10100

spring:
  application:
    name: sujiakeji-product
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    jdbcUrl: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/sujiakeji?useUnicode=true&characterEncoding=utf8
    username: dev
    password: dev
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: dev
    password: dev

mybatis:
  mapperLocations: classpath:mapper/*.xml
  typeAliasesPackage: com.sujiakeji.product.domain
  typeHandlersPackage: com.sujiakeji.product.mybatis.handler

storage:
  baseUrl: http://${STORAGE_HOST}:${STORAGE_PORT}

logging:
  level:
    root: WARN
    com.sujiakeji.product.mapper: TRACE

management:
  endpoints:
    web:
      exposure:
        include: '*'

