server:
  port: 10300

spring:
  application:
    name: sujiakeji-product
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: dev
    password: dev

storage:
  baseUrl: http://${STORAGE_HOST}:${STORAGE_PORT}

merchantService:
  baseUrl: http://sujiakeji-merchant

userService:
  baseUrl: http://sujiakeji-user

logging:
  level:
    root: WARN
    com.sujiakeji.product.mapper: TRACE

management:
  endpoints:
    web:
      exposure:
        include: '*'

